# -*- coding: utf-8 -*-
"""MaratonaDataScience_Python_Fase2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lE0Llx4NjEmM26t_WFIyBdJDrGLZGhvA

Crie um algoritmo em Python que peça 2 números e imprima o maior deles.
"""

a = int(input("Entre com um número inteiro: "))
b = int(input("Entre com outro número inteiro: "))

if a > b:
  print(f"O maior número é: {a}")
elif b > a:
  print(f"O maior número é: {b}")
else:
  print("Os números são iguais!!!")

"""Crie um algoritmo em Python que peça um valor e mostre na tela se o valor é positivo ou negativo."""

a = float(input("Entre com um número: "))

if a > 0:
  print(f"O número {a} é positivo! ")
elif a < 0:
  print(f"O número {a} é negativo! ")
else:
  print("Você encontrou com o zero!!!")

"""Crie um algoritmo em Python que verifique se uma letra digitada é vogal ou consoante."""

letra = input("Entre com uma letra: ")
if letra == "a" or letra == "e" or letra == "i" or letra == "o" or letra == "u":
  print("Esta letra é uma vogal.")
else:
  print("Esta letra é uma consoante.")

"""Faça um programa para a leitura de duas notas parciais de um aluno. O programa deve calcular a média alcançada por aluno e apresentar:
* "Aprovado", se a média alcançada for maior ou igual a sete;
* "Reprovado", se a média for menor do que sete;
* "Aprovado com Distinção", se a média for igual a 10.
"""

a = float(input("Entre com a primeira nota: "))
b = float(input("Entre com a segunda nota: "))
c = float(input("Entre com a terceira nota: "))
d = float(input("Entre com a quarta nota: "))
media = (a+b+c+d)/4

if media == 10:
  print(f"Sua média foi: {media}! Você foi APROVADO COM DISTINÇÃO!!!")
elif media >= 7:
  print(f"Sua média foi: {media}! Você foi APROVADO!!!")
else:
  print(f"Sua média foi: {media}! Você foi REPROVADO!!!")

"""Crie um algoritmo em Python que leia três números e mostre o maior deles."""

a = float(input("Entre com o primeiro número: "))
b = float(input("Entre com o segundo número: "))
c = float(input("Entre com o terceiro número: "))

if a > b and a > c:
  print(f"O maior número é: {a}")
elif b > a and b > c:
  print(f"O maior número é: {b}")
else:  
  print(f"O maior número é: {c}")

"""Crie um algoritmo em Python que leia três números e mostre o maior e o menor deles."""

a = float(input("Entre com o primeiro número: "))
b = float(input("Entre com o segundo número: "))
c = float(input("Entre com o terceiro número: "))

if a > b and a > c:
  print(f"O maior número é: {a}")
  if b > c:
    print(f"O menor número é: {c}")
  else:
    print(f"O menor número é: {b}")

elif b > a and b > c:
  print(f"O maior número é: {b}")
  if a > c:
    print(f"O menor número é: {c}")
  else:
    print(f"O menor número é: {a}")

else:  
  print(f"O maior número é: {c}")
  if a > b:
    print(f"O menor número é: {b}")
  else:
    print(f"O menor número é: {a}")

"""Faça um programa que pergunte o preço de 5 produtos e informe qual produto você deve comprar, sabendo que a decisão é sempre pelo mais barato."""

prod1 = float(input("Informe o preço do produto 1:"))
prod2 = float(input("Informe o preço do produto 2:"))
prod3 = float(input("Informe o preço do produto 3:"))
prod4 = float(input("Informe o preço do produto 4:"))
prod5 = float(input("Informe o preço do produto 5:"))

if prod1 < prod2 and prod1 < prod3 and prod1 < prod4 and prod1 < prod5 :
  print(f"Compre o produto 1, ele está mais barato! Valor: R$ {prod1}")
elif prod2 < prod1 and prod2 < prod3 and prod2 < prod4 and prod2 < prod5 :
  print(f"Compre o produto 2, ele está mais barato! Valor: R$ {prod2}")
elif prod3 < prod1 and prod3 < prod2 and prod3 < prod4 and prod3 < prod5 :
  print(f"Compre o produto 3, ele está mais barato! Valor: R$ {prod3}")
elif prod4 < prod1 and prod4 < prod2 and prod4 < prod3 and prod4 < prod5 :
  print(f"Compre o produto 4, ele está mais barato! Valor: R$ {prod4}")
else:
  print(f"Compre o produto 5, ele está mais barato! Valor: R$ {prod5}")

"""Crie um algoritmo em Python que leia três números e mostre-os em ordem decrescente."""

a = float(input("Entre com o primeiro número: "))
b = float(input("Entre com o segundo número: "))
c = float(input("Entre com o terceiro número: "))

if a>b and a>c:
  if b>c:
    print(f"Ordem decrescente: {a}, {b} e {c}")
  else:
    print(f"Ordem decrescente: {a}, {c} e {b}")
elif b>a and b>c:
  if a>c:
    print(f"Ordem decrescente: {b}, {a} e {c}")
  else:
    print(f"Ordem decrescente: {b}, {c} e {a}")
else:
   if a>b:
    print(f"Ordem decrescente: {c}, {a} e {b}")
   else:
    print(f"Ordem decrescente: {c}, {b} e {a}")

"""As Organizações Mendéz resolveram dar um aumento de salário aos seus colaboradores e lhe contraram para desenvolver o programa que calculará os reajustes em Python. Faça um programa que receba o salário de um colaborador e o reajuste segundo o seguinte critério, baseado no salário atual:

* salários entre 680,00 e 800,00 : aumento de 15%<br>
* salários entre 800,00 e 2500,00 : aumento de 10%<br>
* salários de 2500,00 em diante : aumento de 5% após o aumento ser realizado.

Informe na tela:
* o salário antes do reajuste;
* o percentual de aumento aplicado;
* o valor do aumento;
* o novo salário, após o aumento.
"""

salario = float(input("Entre com o seu salário: R$ "))
if salario >= 2500:
  print(f"Seu salário de {salario} vai receber um reajuste de 5%. Novo valor: {round(salario * 1.05, 2)}")
elif salario <= 800:
  print(f"Seu salário de {salario} vai receber um reajuste de 15%. Novo valor: {round(salario * 1.15, 2)}")
else:
  print(f"Seu salário de {salario} vai receber um reajuste de 10%. Novo valor: {round(salario * 1.10, 2)}")