# -*- coding: utf-8 -*-
"""MaratonaDataScience_Python_Fase3a.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n3AEDovVKWjCOK6W0gAEUO3_79d5CPiT

Crie um algoritmo em Python que peça uma nota, entre zero e 100. Mostre uma mensagem caso o valor seja inválido e continue pedindo até que o usuário informe um valor válido.
"""

nota = int(input("Entre com uma nota entre 0 e 100: "))

while nota>100:
  print("Valor inválido!!!")
  nota = int(input("Entre com uma nota entre 0 e 100: "))

print(f"A nota digitada foi: {nota}")

"""Crie um algoritmo em Python que leia um nome de usuário e a sua senha e não aceite a senha igual ao nome do usuário, mostrando uma mensagem de erro e voltando a pedir as informações.<br>"""

usuario = input("Entre com o nome do usuário: ")
senha = input("Entre com a senha: ")

while usuario == senha:
  print("Erro! Senha igual ao nome de usuário!")
  usuario = input("Entre com o nome do usuário: ")
  senha = input("Entre com a senha: ")

print(f"O usuário {usuario} foi cadastrado com sucesso!!!")

"""Crie um algoritmo em Python que leia e valide as seguintes informações:
* Nome: maior que 3 caracteres;
* Idade: entre 0 e 150;
* Salário: maior que zero;
* Sexo: 'f' ou 'm';
* Estado Civil: 's', 'c', 'v', 'd';
"""

nome = input("Entre com o seu nome: ")
while len(nome) < 4:
  print("O nome precisa ter mais que 3 caracteres! Tente novamente... ")
  nome = input("Entre com o seu nome!")

idade = int(input("Entre com a sua idade: "))
while idade > 150 :
  print("A idade precisa estar entre 0 e 150! Tente novamente... ")
  idade = int(input("Entre com a sua idade: "))

salario = float(input("Entre com o seu salário: R$"))
while salario < 0:
  print("Salário inválido! Tente novamente...")
  salario = float(input("Entre com o seu salário: R$"))

sexo = input("Entre com o seu sexo (m/f): ")
while sexo != "m" and sexo != "f" :
  print("Inválido! Entre com 'm' para masculino e 'f' para feminino!")
  sexo = input("Entre com o seu sexo (m/f): ")

estadoCivil = input("Entre com o seu estado civil(s/c/v/d): ")
while estadoCivil != "s" and estadoCivil != "c" and estadoCivil != "v" and estadoCivil != "d" :
  print("Inválido! Entre com 's' para solteiro, 'c' para casado, 'v' para viuvo, 'd' para divorciado: ")
  estadoCivil = input("Entre com o seu estado civil(s/c/v/d): ")

print("Programa finalizado! :)")

"""Supondo que a população de um país A seja da ordem de 80000 habitantes com uma taxa anual de crescimento de 3% e que a população de B seja 200000 habitantes com uma taxa de crescimento de 1.5%.<br><br> Crie um algoritmo em Python que calcule e escreva o número de anos necessários para que a população do país A ultrapasse ou iguale a população do país B, mantidas as taxas de crescimento."""

popA = 80000
popB = 200000
taxaA = 1.03
taxaB = 1.015

i = 0
while popB > popA:
  popA = popA * taxaA
  popB = popB * taxaB
  i = i + 1

print(f"O número de anos para a população do país A ultrapassar o país B é: {i} ")

"""Desenvolva um gerador de tabuada, capaz de gerar a tabuada de qualquer número inteiro entre 1 a 10. O usuário deve informar de qual numero ele deseja ver a tabuada. A saída deve ser conforme o exemplo abaixo:
Tabuada de 5:<br>
5 X 1 = 5<br>
5 X 2 = 10<br>
...<br>
5 X 10 = 50<br>
"""

tabuada = int(input("Digite qual tabuada você quer saber: "))
print(f"Tabuada do número: {tabuada} ")

for valor in range(1,11,1):
  print(f"Tabuada do {tabuada}: {tabuada} x {valor} = {tabuada*valor}"  )

"""Crie um algoritmo em Python que leia três números e mostre o maior e o menor deles."""

a = int(input("Entre com o primeiro número inteiro: "))
b = int(input("Entre com o segundo número inteiro: "))
c = int(input("Entre com o terceiro número inteiro: "))

if a>b and a>c:
  print(f"O maior número é {a}.")
  if b<c:
    print(f"O menor número é {b}.")
  else:
    print(f"O menor número é {c}.")

elif b>a and b>c:
  print(f"O maior número é {b}.")
  if a<c:
    print(f"O menor número é {a}.")
  else:
    print(f"O menor número é {c}.")

else:
  print(f"O maior número é {c}.")
  if b<a:
    print(f"O menor número é {b}.")
  else:
    print(f"O menor número é {a}.")

"""Crie um algoritmo em Python que peça 2 números, base e expoente, calcule e mostre o primeiro número elevado ao segundo número. Não utilize a função de potência da linguagem."""

a = int(input("Entre com o primeiro número(base): "))
b = int(input("Entre com o segundo número(expoente): "))

i=1
new = a
while b>i :
  new = new*a
  i=i+1

if b == 0:
  print("Todo número elevado a zero é 1!")
elif b == 1:
  print(f"Todo número elevado a 1 é ele mesmo! No caso: {a}")
else:
  print(f"O valor da base elevado ao expoente é: {new} ")

"""Crie um algoritmo em Python que peça 10 números inteiros, calcule e mostre a quantidade de números pares e a quantidade de números impares."""

a = int(input("Entre com o primeiro número inteiro: "))
b = int(input("Entre com o segundo número inteiro: "))
c = int(input("Entre com o terceiro número inteiro: "))
d = int(input("Entre com o quarto número inteiro: "))
e = int(input("Entre com o quinto número inteiro: "))

lista = [a,b,c,d,e]
#print(lista)
#type(lista)
contPar = 0
total = len(lista)
print(f"Qtde de entradas: {total}")

for i in range(0,total):
  if lista[i]%2 == 0:
    lista_par = lista[i]
    #print(lista_par)
    contPar = contPar + 1

print(f"Qtde de números pares: {contPar}")
print(f"Qtde de números ímpares: {total - contPar}")

"""Um funcionário de uma empresa recebe aumento salarial anualmente: Sabe-se que:
Esse funcionário foi contratado em 1995, com salário inicial de R$ 1.000,00;
Em 1996 recebeu aumento de 1,5% sobre seu salário inicial;
A partir de 1997 (inclusive), os aumentos salariais sempre correspondem ao dobro do percentual do ano anterior. Crie um algoritmo em Python que determine o salário atual desse funcionário. Após concluir isto, altere o programa permitindo que o usuário digite o salário inicial do funcionário.
"""

#salario1995 = 1000
aumento = 1.015

salario = float(input("Entre com o salário a ser calculado o reajuste: "))
ano = 1995
salarioNew = salario

while ano < 2020:
  salarioNew = salarioNew*1.015
  ano = ano + 1

print(f"O salário reajustado para o ano de 2020 é: {round(salarioNew,2)} ")

"""Crie um algoritmo em Python com uma função que necessite de um argumento. A função retorna o valor de caractere ‘P’, se seu argumento for positivo, e ‘N’, se seu argumento for zero ou negativo."""

def funcao_teste(x):
  if x>0:
    return "P"
  else:
    return "N"

funcao_teste(2)

"""Construa uma função que receba uma data no formato DD/MM/AAAA e devolva uma string no formato D de mesPorExtenso de AAAA. Opcionalmente, valide a data e retorne NULL caso a data seja inválida."""

def func_data(x,y,z):
  if y == 1:
    mes = " de janeiro "
  elif y == 2:
    mes = " de fevereiro "
  else:
    mes = " de marco-dezembro "
  return str(x) + mes + str(z)


func_data(1,1,2021)

"""Crie uma classe que modele uma pessoa:<br>

Atributos: nome, idade, peso e altura<br>
Métodos: Envelhercer, engordar, emagrecer, crescer.<br>
<br>Obs: Por padrão, a cada ano que nossa pessoa envelhece, sendo a idade dela menor que 21 anos, ela deve crescer 0,5 cm.
"""

class Pessoa:
    def __init__(self, nome: str, idade: int, peso: float, altura: float):
        self.nome = nome
        self.idade = idade
        self.peso = peso
        self.altura = altura

    def envelhecer(self):
        while self.idade < 21:
            self.altura = self.altura + 0.5
            self.idade = self.idade + 1

    def engordar(self, peso):
        self.peso += peso

    def emagrecer(self, peso):
        self.peso -= peso

    def crescer(self, altura):
        self.altura += altura


    def mostraPessoa(self):
        print(f'Nome: {self.nome}, idade: {self.idade} anos, peso: {self.peso}kg, altura: {self.altura}cm')


p1 = Pessoa('João', 19, 78, 188)
p1.mostraPessoa()
p1.envelhecer()
#p1.emagrecer()
p1.mostraPessoa()