# -*- coding: utf-8 -*-
"""MaratonaDataScience_Python_Fase1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IokACfSkZQj0sMaX5c0e9NwvsiwFvThb

Crie um algoritmo em Python que mostre a mensagem "Alo mundo" na tela.
"""

print("Alô, mundão sem porteira!")

"""Crie um algoritmo em Python que peça dois números e imprima a soma."""

a = float(input("Entre com um número: "))
b = float(input("Entre com outro número: "))
soma = a + b

print(f"A soma dos dois números é: {soma}")

"""Crie um algoritmo em Python que peça um número e então mostre a mensagem O número informado foi [número]."""

numero = float(input("Entre com um número: "))
print(f"O número informado foi: {numero}")

"""Crie um algoritmo em Python que converta metros para centímetros."""

metro = float(input("Entre com a metragem (em metros) para conversão: "))
centimetro = metro * 100
print(f"{metro} corresponde a {centimetro} centímetros")

"""Crie um algoritmo em Python que peça as 4 notas bimestrais e mostre a média."""

a = float(input("Entre com a primeira nota bimestral: "))
b = float(input("Entre com a segunda nota bimestral: "))
c = float(input("Entre com a terceira nota bimestral: "))
d = float(input("Entre com a quarta nota bimestral: "))

media = (a+b+c+d) / 4

print(f"A média obtida nos bimestres é {media}: ")

"""Crie um algoritmo em Python que peça o raio de um círculo, calcule e mostre sua área."""

# A área de um círculo é pi vezes o raio elevado ao quadrado (A = π r²)

import math

pi = math.pi
raio = float(input("Entre com o valor do raio do círculo para cálculo da área: "))

area = pi * (raio**2)

print(f"O valor da área é: {area}")

"""Crie um algoritmo em Python que calcule a área de um quadrado, em seguida mostre o dobro desta área para o usuário."""

a = float(input("Entre com o valor do lado do quadrado: "))
area = a * a
dobro = area * 2
print(f"A área do quadrado calculada é: {area}")
print(f"O dobro da área é: {dobro}")

"""Crie um algoritmo em Python que pergunte quanto você ganha por hora e o número de horas trabalhadas no mês. Calcule e mostre o total do seu salário no referido mês.

"""

valor_hora = float(input("Entre com o valor que você ganha por hora: "))
horas_mes = float(input("Entre com as horas trabalhadas no mês: "))

salario = valor_hora * horas_mes

print(f"O valor do salário é: {salario}")

"""Crie um algoritmo em Python que peça a temperatura em graus Farenheit, transforme e mostre a temperatura em graus Celsius.
C = (5 * (F-32) / 9).
"""

#(32 °F − 32) × 5/9 = 0 °C

faren = float(input("Entre com a temperatura em Farenheit: "))
celsius = ((faren - 32) *  5 / 9)

print(f"{faren} em Farenheit corresponde a {round(celsius,2)} Celsius.")

"""Crie um algoritmo em Python que peça a temperatura em graus Celsius, transforme e mostre em graus Farenheit."""

# (0 °C × 9/5) + 32 = 32 °F


celsius = float(input("Entre com a temperatura em Celsius: "))
faren = ((celsius * 9/5) + 32)

print(f"{celsius} em Farenheit corresponde a {round(faren,2)} Celsius.")

"""Crie um algoritmo em Python que peça 2 números inteiros e um número real. Calcule e mostre:
* a soma do dobro do primeiro com metade do segundo .
* a soma do triplo do primeiro com o terceiro.
* o terceiro elevado ao cubo.
"""

a = int(input("Entre com o primeiro número inteiro: "))
b = int(input("Entre com o segundo número inteiro: "))
c = float(input("Entre com o primeiro número real: "))

val1 = (a * 2) + (b / 2)
val2 = (a * 3) + c
val3 = c**3

print(f"A soma do dobro do primeiro com metade do segundo é: {val1}")
print(f"A soma do triplo do primeiro com o terceiro é: {val2}")
print(f"O terceiro elevado ao cubo é: {val3}")